spring:
  datasource:
    url: jdbc:mysql://db:3306/test_sql #jdbc:mysql://${MYSQL_HOST:localhost}:6033/test_sql
    username: bguntupalli
    password: password
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: true